apiVersion: v1
kind: ConfigMap
metadata:
  name: extension-apiserver-authentication
  namespace: kube-system
data:
  client-ca-file: |
    {{ .CABundle }}
  requestheader-allowed-names: '["front-proxy-client"]'
  requestheader-client-ca-file: |
    {{ .ReqCABundle }}
  requestheader-extra-headers-prefix: '["X-Remote-Extra-"]'
  requestheader-group-headers: '["X-Remote-Group"]'
  requestheader-username-headers: '["X-Remote-User"]'
