apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: open-cluster-management:managedclusters:{{ .OrgWorkspaceName }}
  annotations:
    kcp.dev/cluster: root
  labels:
    workspaces.kcp.dev/name: {{ .OrgWorkspaceName }}
rules:
- apiGroups:
  - tenancy.kcp.dev
  resources:
  - workspaces/content
  resourceNames:
  - {{ .OrgWorkspaceName }}
  verbs:
  - access
