apiVersion: v1
kind: Service
metadata:
  name: cluster-manager-work-webhook
  namespace: {{ .ClusterManagerName }}
spec:
  type: NodePort
  selector:
    app: {{ .ClusterManagerName }}-work-webhook
  ports:
  - port: 443
    targetPort: 6443
    nodePort: {{ .WorkWebhookNodePort }}
