apiVersion: v1
kind: Service
metadata:
  name: cluster-manager-registration-webhook
  namespace: {{ .ClusterManagerName }}
spec:
  type: NodePort
  selector:
    app: {{ .ClusterManagerName }}-registration-webhook
  ports:
  - port: 443
    targetPort: 6443
    nodePort: 30443
